# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: lidingoslalom_development
  pool: 5
  username: Joel
  password: 
  timeout: 5000

test:
  adapter: postgresql
  database: lidingoslalom_test
  pool: 5
  username: Joel
  password: 
  timeout: 5000
